CIMS/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('django-admin/', include('admin.urls')),
    path('', include('my_app.urls')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

my_app/urls.py
from django.urls import path
from . import views
from .views import line_chart, line_chart_json


urlpatterns = [
   # users paths
   path('chart', line_chart, name='line_chart'),
    path('chartJSON', line_chart_json, name='line_chart_json'),
   path('register/',views.register, name='register'),
    path('faculty_reg',views.faculty_reg, name='faculty_reg'),
   path('nstp_reg',views.nstp_reg, name='nstp_reg'),
#    path('rotc_reg',views.rotc_reg, name='rotc_reg'),
   path('staff_reg',views.staff_reg, name='staff_reg'),
   path('register/addRecord/',views.addRecord, name='addRecord'),
   path('faculty_addRecord/',views.faculty_addRecord, name='faculty_addRecord'),
   path('nstp_addRecord/',views.nstp_addRecord, name='nstp_addRecord'),
   path('staff_addRecord/',views.staff_addRecord, name='staff_addRecord'),
#    path('rotc_addRecord/',views.rotc_addRecord, name='rotc_addRecord'),
#    path('register/upload/', views.image_upload_view),
   path('login',views.user_login, name='user_login'),
   path('submitlogin/',views.usersubmitlogin, name='usersubmitlogin'),
   
   path('home/',views.user_home_page, name='user_home_page'),
   path('med_inquiry/',views.med_inquiry, name='med_inquiry'),
   path('home/upload_prof_pic/',views.upload_prof_pic, name='upload_prof_pic'),
   path('home/edit_user_profile',views.edit_user_profile, name='edit_user_profile'),
   path('home/submit_post/',views.submit_post, name='submit_post'),
   path('',views.user_login, name='index'),
   path('logout/',views.user_logout, name='user_logout'),
   path('qualified_rotc',views.qualified_rotc, name='qualified_rotc'),
   path('qualified_cwts',views.qualified_cwts, name='qualified_cwts'),
  
    # admin paths

    path('admin/register/',views.admin_register, name='admin_register'),
    path('admin/register/adminSubmitReg/',views.adminSubmitReg, name='adminSubmitReg'),
    path('comment/<int:pk>',views.comment,name='comment'),
    path('admin/',views.admin_home_page, name='admin_home_page'),
    path('admin/home/',views.admin_home_page, name='admin_home_page'),  
    path('admin/faculty_list',views.faculty_list, name='faculty_list'),
    
    path('admin/add_category',views.add_category, name='add_category'),
    
    path('admin/rotc_qualified',views.qualified_rotc_list, name='admin_users_list'),
    path('admin/users_list',views.admin_users_list, name='admin_users_list'),
    path('admin/users_list/view_by_level',views.view_by_level, name='view_by_level'),
    path('admin/bulk-delete',views.bulk_delete, name='bulk_delete'),
    path('admin/deleted-users',views.deleted_users, name='deleted_users'),
    path('admin/restore_user/<int:id>',views.restore_user, name='restore_user'),
    
    path('admin/with_condition',views.with_condition, name='with_condition'),
    path('admin/home/delete_post/<int:pk>',views.delete_post,name='delete_post'),
    path('admin/home/view_post/<int:pk>',views.view_post,name='view_post'),
    path('features/submit_post/',views.submit_post, name='submit_post'),
    path('admin/login/',views.admin_login, name='admin_login'),
    path('admin/login/submitlogin/',views.adminsubmitlogin, name='adminsubmitlogin'),
    path('admin/logout/',views.admin_logout, name='admin_logout'),
    path('admin/delete_user/<int:pk>', views.delete_user, name='delete_user'),
    path('admin/for_confirmation',views.admin_for_confirmation, name='admin_for_confirmation'),
    path('admin/confirm_user/<int:pk>', views.confirm_user, name="confirm_user"),
    path('admin/edit_user/<int:pk>', views.edit_user, name="edit_user"),
    path('admin/edit_user/save_edit_user/<int:pk>', views.save_edit_user, name="save_edit_user"),
    path('admin/check_user/<int:id>', views.check_user, name="check_user"),
    path('admin/inventory',views.admin_inventory, name='admin_inventory'),
    path('admin/inventory/remove_order/<int:pk>',views.remove_order, name='remove_order'),
    path('admin/inventory/check_out_order',views.check_out_order, name='check_out_order'),
    path('admin/inventory/add_order',views.add_order, name='add_order'),
    path('admin/inventory/list',views.list_by, name='list_by'),
    path('admin/inventory/add_stock/<int:pk>',views.add_stock, name='add_stock'),
    path('admin/inventory/delete_stock/<int:pk>',views.delete_stock, name='delete_stock'),
     path('admin/inventory/add_stock/save_added_stock/<int:pk>',views.save_added_stock, name='save_added_stock'),
    path('admin/inventory/expired',views.expired, name='expired'),
    path('admin/inventory/save',views.save_item, name='save_item'),
    path('features',views.features,name='features'),
    path('message',views.message,name='message'),
    path('features/announcements',views.announcements,name="announcements"),
    path('send',views.send,name='send'),
    path('visit_history',views.visit_history,name='visit_history'),
    path('medical_notes',views.medical_notes,name='medical_notes'),
    path('search_history',views.search_history,name='search_history'),
    path('save_current_checkup_rec',views.save_current_checkup_rec,name='save_current_checkup_rec'),
    path('reports',views.reports,name='reports'),
    path('settings',views.settings,name='settings'),
    path('myhistory',views.myhistory,name='myhistory'),
    path('physicaly_fit',views.physicaly_fit,name='physicaly_fit'),
    path('pdftest',views.pdftest,name='pdftest'),
    path('save_code',views.save_code,name='save_code'),
    
    path('privacy-policy',views.privacy_policy,name='privacy_policy'),
    path('notifications',views.notifications,name='notifications'),
    path('view-notif/<int:id>',views.view_notif,name='view_notif'),
    
    
    #reports
    path('reports/inventory',views.reports_inventory,name='reports_inventory'),
    path('reports/user-visit-history/<int:id>',views.reports_user_visit_history,name='user_visit_history'),
]

my_app/models.py
from django.db import models
from django.utils import timezone
class Users(models.Model):
  gen=[('',''),('Male','Male'),('Female','Female')]
  dep=[('',''),('BSIT','BSIT'),('BSHRM','BSHRM'),('BSED','BSED'),('CRIM','CRIM')]
  medstat=[('',''),('Physically Fit','Physically Fit'),('With Medical Condition','With Medical Condition')]
  year=[('',''),('Freshmen','Freshmen'),('Sophomore','Sophomore'),('Junior','Junior'),('Senior','Senior')]
  student_id = models.CharField(max_length=255, default=None, null=True, blank=True)
  firstname = models.CharField(max_length=255)
  middlename = models.CharField(max_length=255)
  lastname = models.CharField(max_length=255)
  birthday = models.DateField(max_length=255)
  age = models.CharField(max_length=255)
  address = models.CharField(max_length=255)
  gender = models.CharField(max_length=25,choices=gen,default='')
  year_level = models.CharField(max_length=20,choices=year,default='')
  department = models.CharField(max_length=25,choices=dep,default='', blank=True, null= True)
  email = models.EmailField(max_length=255)
  password = models.CharField(max_length=255)
  status = models.CharField(max_length=225)
  medical_status = models.CharField(max_length=200,choices=medstat, default='', blank=True, null= True)
  medical_condition = models.CharField(max_length=100, default="N/A", blank=True, null= True)
  medcert = models.ImageField(upload_to='medcert', blank=True, null= True, default='medcert/default.jpg')  
  user_type =  models.CharField(max_length=20)
  list_filter =  models.CharField(max_length=20)
  is_online = models.CharField(max_length=10,default='false')
  is_active = models.BooleanField(default=True)
  date_added = models.DateTimeField(default=timezone.now) 

  def __str__(self):
    return "%s %s"%(self.firstname,self.lastname)
  
class Admin(models.Model):
  email = models.EmailField(max_length=225)
  password = models.CharField(max_length=255)
  profile_pic = models.ImageField(upload_to='profile_pic')
  
class Category(models.Model):
  name = models.CharField(max_length=50)

class Inventory(models.Model):
  unit=[('',''),('Pieces','Pieces'),('Bottle','Bottle'),('Litter','Litter'),('Stab','Stab')]
  serial = models.IntegerField()
  item_name = models.CharField(max_length=255)
  purchase_date = models.DateField(max_length=255)
  # selling_price = models.FloatField(max_length=255)
  quantity = models.IntegerField()
  expiration = models.DateField(max_length=255)
  item_image = models.ImageField(upload_to='inventory')
  unit = models.CharField(max_length=255,choices=unit,default='')
  category = models.CharField(max_length=255, default='')
  remaining = models.IntegerField(default=0)
  status = models.CharField(max_length=225)
  
  def save(self, *args, **kwargs):
    #perform auto increment serial here
    inv = Inventory.objects.all()
    if not self.pk:
      if inv.exists():
        self.serial = inv.last().serial + 1
      else:
        self.serial = 1 
        
      self.remaining = self.quantity    
    super(Inventory, self).save(*args, **kwargs)

class Posts(models.Model):
  content = models.TextField(max_length=50000)
  title = models.CharField(max_length=255)
  date_posted = models.DateField(auto_now_add=True)
  posted_by = models.CharField(max_length=255,default="")

class Faculty(models.Model):
  gen=[('',''),('Male','Male'),('Female','Female')]
  dep=[('',''),('BSIT','BSIT'),('BSHRM','BSHRM'),('BSED','BSED'),('CRIM','CRIM')]
  medstat=[('',''),('Physically Fit','Physically Fit'),('With Medical Condition','With Medical Condition')]
  firstname = models.CharField(max_length=255)
  middlename = models.CharField(max_length=255)
  lastname = models.CharField(max_length=255)
  birthday = models.DateField(max_length=255)
  age = models.CharField(max_length=255)
  address = models.CharField(max_length=255)
  gender = models.CharField(max_length=25,choices=gen,default='')
  department = models.CharField(max_length=25,choices=dep,default='')
  email = models.EmailField(max_length=255)
  password = models.CharField(max_length=255)
  status = models.CharField(max_length=225)
  user_type =  models.CharField(max_length=20)

class Order(models.Model):
  item_name = models.CharField(max_length=255) 
  item_category = models.CharField(max_length=255) 
  serial = models.IntegerField()
  quantity = models.IntegerField()
  selling_price = models.FloatField(max_length=255,default=0)
  unit = models.CharField(max_length=255)
  student_name = models.CharField(max_length=100)
  total = models.FloatField(default=0)
  order_status = models.CharField(max_length=255) 
  order_date = models.DateTimeField(default=timezone.now)

class PostImage(models.Model):
  post_id = models.IntegerField()
  post_pic = models.ImageField(upload_to='post')

class ProfilePics(models.Model):
  prof_pic_of = models.CharField(max_length=50,default='')
  profile_pic = models.ImageField(upload_to='profile_pic')

class Comments(models.Model):
  post_id = models.IntegerField(default=0)
  commented_by = models.CharField(max_length=225,default="")
  comment = models.TextField(max_length=50000)

class Messages(models.Model):
  message = models.TextField(max_length=50000)
  message_from = models.CharField(max_length=30)
  message_to = models.CharField(max_length=30)
  date = models.DateField(auto_now_add=True)

class Reply(models.Model):
  msg_id = models.IntegerField(default=0)
  msgrep = models.TextField(max_length=50000)
  msgrep_from = models.CharField(max_length=30)
  msgrep_to = models.CharField(max_length=30)
  date = models.DateField(auto_now_add=True)

class CheckUpRecords(models.Model):
  rec_id = models.CharField(default='' , max_length=255)
  rec_email = models.EmailField(max_length=50)
  checkup_date = models.DateField(auto_now_add=True)
  blood_pressure = models.CharField(max_length=30)
  pulse_rate = models.CharField(max_length=100)
  respiratory_rate = models.CharField(max_length=100)
  temperature = models.CharField(max_length=30)
  other_info = models.TextField(max_length=50000)
  remark_after_checkup = models.TextField(max_length=50000)

class RegCode(models.Model):
  faculty=models.CharField(max_length=50,default="None")
  staff=models.CharField(max_length=50,default="None")
  nstp_coordinator=models.CharField(max_length=50,default="None")
  admin=models.CharField(max_length=50)
  rotc_coordinator=models.CharField(max_length=50,default="None")
  
class Search(models.Model):
  search = models.CharField(default='0', max_length=225)
 
class Editors(models.Model):
    editor_name = models.CharField(max_length=200)
    num_users = models.IntegerField()

    def __str__(self):
        return "{}-{}".format(self.editor_name, self.num_users) 

class Notifications(models.Model):
  medicine = models.ForeignKey(Inventory, on_delete=models.CASCADE)
  datetime = models.DateTimeField(auto_now_add=True)
  is_read = models.BooleanField(default=False)

  class DispenseGraph(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.CharField(max_length=255)
    item_number = models.CharField(max_length=255)
    data_date = models.DateTimeField(default=timezone.now)
  

my_app/templates/admin_for_confirmation.html
{% extends "features.html" %}
{% block features_content %}
<a href="{% url 'features' %}"><button>Back</button></a>
    <h1>For Confirmation</h1>
    <table>
        <tr class="table-header">
            <td>ID</td>
            <td>First Name</td>
            <td>Middle Name</td>
            <td>Last Name</td>
            <td>Birth Day</td>
            <td>Age</td>
            <td>Address</td>
            <td>Gender</td>
            <td>Department</td>
            <td>Email</td>
            <td>Medical Status</td>
            <td>Date Added</td>
            <td>Actions</td>
        </tr>
        {% for x in users %}
        <tr>
        <td>{{ x.id }}</td>
        <td>{{ x.firstname }}</td>
        <td>{{ x.middlename }}</td>
        <td>{{ x.lastname }}</td>
        <td>{{ x.birthday }}</td>
        <td>{{ x.age }}</td>
        <td>{{ x.address }}</td>
        <td>{{ x.gender }}</td>
        <td>{{ x.department }}</td>
        <td>{{ x.email }}</td>
        <td>{{ x.medical_status }}</td>
        <td>{{ x.date_added }}</td>
        <td>
            <a href="{% url 'check_user' x.pk %}" type="submit" class="checkbtn"><button>Show</button></a>
        </td>
        </tr>
        {% endfor %}
        </table>
        {% if empty_rec == "" %}
            <div style="padding:1rem; display:flex;flex-wrap:wrap;flex-direction:column;align-content:center; background-color:rgba(255, 0, 0, 0.353);">No Record Found</div>
        {% endif %}
    
{% endblock %}

my_app/templates/admin_inventory.html
{% extends "admin_home_page.html" %}
{% block admin_content %}

<div style=" width: 96%;
padding: 10px;
overflow: hidden;
clear: both;">

<a href="{% url 'features' %}"><button>Back</button></a>
<a href="{% url 'notifications' %}" style="float: right;"><button>Notifications {% if notifs > 0 %} <span style="padding: 5px; background-color: red; color: white; border-radius: 10px;">
    {{notifs}}</span> 
    {% endif %}
</button> </a>
</div>
<h1 style="margin-left: 10px;">Inventory</h1>
<div style="display:grid; grid-template-columns: 200px auto; padding: .5rem; margin-top: .5rem;">

    <div>

        <div
            style="margin-top: .5rem; padding: .5rem; border-radius: .6rem; box-shadow: 0px 2px 8px 0px rgba(0, 0, 0, 0.364);">
            <form action="/admin/inventory/save" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>Add Item</h3>

                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags == 'warning' %}
                            <div style="color: red;">{{ message }}</div>
                        {% elif message.tags == 'success' %}
                            <div style="color: green;">{{ message }}</div>
                        {% endif %} 
                    {% endfor %}
                 {% endif %}

                {% for field in form %}
                <div class="fieldWrapper">
                    
                    {% if field.name == "serial" %}
                        <label>Item</label>
                    {% else %}
                        {{ field.label_tag }}<br>
                    {% endif %}
                    {{ field }}

                    {% if field.name == "category" %}
                    <a href="#" id="openModalBtn" style="margin-top: 30px;"><small>Add Category</small></a>
                    {% endif %}

                    {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>

                {% endfor %}
                <br><button type="submit">Save</button>
            </form>
        </div>
    </div>
    <div style="margin-left: .5rem;">
        <div style="padding: .5rem; ">
            <div>
                <h4>Order Section</h4>
            </div>
            <div style="display:grid;grid-template-columns: 200px auto;  margin-left: .5rem; padding: .5rem; border-radius: .6rem; box-shadow: 0px 2px 8px 0px rgba(0, 0, 0, 0.364);">
                
                <form action="{%url 'add_order'%}" method="post" style="margin-right: 20px;">
                    {% csrf_token %}
                    Item Number:{{order.serial}}<br><br>
                    Quantity:{{order.quantity}}<br><br>
                 
                    Student Name: <input type="text" name="student_name" id="student_name" readonly>
                    <a href="#" id="openStudentList" style="margin-top: 20px;"><span>Select Student</span></a><br><br>
                  
                    <button style=" margin-top: .5rem; width:100%;">Enter</button>
                </form>

                <div>
                    <table>
                        {% for message in messages %}
                            {% if message.tags == 'error' %}
                                <h3 style="color:red;">!!!{{message}}</h3>
                            {% endif %}
                        {% endfor %}
                       <tr class="table-header">
                            <td>Student Name</td>
                            <td>Item Name</td>
                            <td>Quantity</td>
                            <td>Unit</td>
                            <td>Total</td>
                            <td>Order Date</td>
                            <td>Action</td>
                        </tr>
                        {% for h in all_orders %}
                        <tr>
                            <td>{{h.student_name}}</td>
                            <td>{{h.item_name}}</td>
                            <td>{{h.quantity}}</td>
                            <td>{{h.unit}}</td>
                            <td>{{h.total}}</td>
                            <td>{{h.order_date}}</td>
                            <td>
                                <a href="{%url 'remove_order' h.pk %}" type="submit"
                                    class="btn"><button>Remove</button></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                    {% if empty_rec == "" %}
                    <div
                        style="padding:1rem; display:flex;flex-wrap:wrap;flex-direction:column;align-content:center; background-color:rgba(255, 0, 0, 0.353);">
                        Enter Medicine</div>
                    {% endif %}
                    <div
                        style="margin-top: .5rem; display: flex; flex-wrap: wrap; flex-direction: column; align-content:flex-end;">
                        <form action="{%url 'check_out_order'%}" method="post">
                            <button>Dispense from Inventory</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div
            style="display:flex;flex-wrap: wrap;flex-direction: column;align-content: center; border-radius: .5rem;padding:.5rem;box-shadow: 0px 2px 4px 2px rgba(0, 0, 0, 0.372);">
            <form action="/admin/inventory/list">
                <h2>List Filter</h2>
                <h4>Medicine for:&nbsp;{{form.category}}</h4>
                <button style="width: 100%;">Display</button>
            </form>
        </div>
        <h2>Medicine(s) for&nbsp;{{table_title}}</h2>
        <a href="/reports/inventory" target="_blank"><button>Print Inventory Report</button></a>
        <table style="margin-top:1rem ;">
            <tr class="table-header">
                <td>Item Number</td>
                <td>Name</td>
                <td>Category</td>
                <td>Date Purchased</td>

                <td>Unit</td>
                <td>Quantity</td>
                <td>Remaining</td>
                <td>Expitation Date</td>
                <td>Image</td>
                <td>Actions</td>
            </tr>
            <tr>{% for x in items %}
                <td>{{x.serial}}</td>
                <td>{{x.item_name}}</td>
                <td>{{x.category}}</td>
                <td>{{x.purchase_date}}</td>

                <td>{{x.unit}}</td>
                <td>{{x.quantity}}</td>
                <td>{{x.remaining}}</td>
                <td>{{x.expiration}}</td>
                <td><img src="{{ x.item_image.url }}" style="height:100px; width:100px;"></td>
                <td>
                    <a href="{% url 'add_stock' x.pk %}" type="submit" class="btn"><button>Add Stocks</button></a>
                    <a href="{% url 'delete_stock' x.pk %}" type="submit" class="btn"><button>Delete</button></a>
                </td>
            </tr> {% endfor %}
        </table>
        {% if empty_rec == "" %}
        <div
            style="padding:1rem; display:flex;flex-wrap:wrap;flex-direction:column;align-content:center; background-color:rgba(255, 0, 0, 0.353);">
            No Record Found</div>
        {% endif %}
    </div>
</div>

<style>
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.5);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
        max-width: 600px;
    }

    .modal-lg{
        max-width: 800px;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
        cursor: pointer;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    #id_unit, #id_category{
            width: 100%;
            background:white;
            padding: .5rem;
            border-radius: .5rem;
            
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.392);
    }

    .dataTables_filter {
      margin-bottom: 10px; /* Adjust the bottom margin to increase or decrease the distance */
    }

</style>

<div id="myModal" class="modal">
    <div class="modal-content">
        <span id="closeModalBtn" class="close">&times;</span>
        <h2>New Category</h2>
       
        <form action="/admin/add_category" id="category_form" method="POST">
            <input type="text" required placeholder="Category Name" style="margin-bottom: 10px;" name="name">
            <button id="save_category" style="margin-bottom: 10px;">Save</button>
        </form>

    </div>
</div>

<div id="studentListModal" class="modal">
    <div class="modal-content modal-lg">
        <span id="closeStudentList" class="close">&times;</span>
        <h2>Select Student</h2>

        <table id="students">
            <thead>
                <tr class="table-header">
                    <th>Student Name</th>
                    <th>Department</th>
                    <th>Address</th>
                    <th>---</th>
                </tr>
            </thead>
            <tbody>
                {% for stud in students %}
                <tr>
                    <td>{{stud.firstname}} {{stud.middlename}} {{stud.lastname}}</td>
                    <td>{{stud.department}}</td>
                    <td>{{stud.address}}</td>
                    <td>
                        <button onclick="select_student(event)" student_name="{{stud.firstname}} {{stud.middlename}} {{stud.lastname}}">Select</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
       

    </div>
</div>



<script>
    var table = document.querySelector("#students")

    var dataTable = new DataTable(table, {
      });

    var openModalBtn = document.getElementById("openModalBtn");
    var closeModalBtn = document.getElementById("closeModalBtn");
    var modal = document.getElementById("myModal");

    // Open the modal
    openModalBtn.addEventListener("click", function () {
        modal.style.display = "block";
    });

    // Close the modal
    closeModalBtn.addEventListener("click", function () {
        modal.style.display = "none";
    });

    // Close the modal when clicking outside the modal content
    window.addEventListener("click", function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    });


    var openStudentList = document.getElementById("openStudentList");
    var closeStudentList = document.getElementById("closeStudentList");
    var studentListModal = document.getElementById("studentListModal");

    // Open the modal
    openStudentList.addEventListener("click", function () {
        studentListModal.style.display = "block";
    });

    // Close the modal
    closeStudentList.addEventListener("click", function () {
        studentListModal.style.display = "none";
    });

    // Close the modal when clicking outside the modal content
    window.addEventListener("click", function (event) {
        if (event.target == studentListModal) {
            studentListModal.style.display = "none";
        }
    });

    function select_student(event){
        event.preventDefault()

        const button = event.target
        const student_name = button.getAttribute('student_name')

        document.querySelector("#student_name").value = student_name
        studentListModal.style.display = "none";    
    }

</script>
{% endblock %}

my_app/templates/admin_users_list.html
{% extends "features.html" %}
{% block features_content %}
<a href="{% url 'features' %}"><button>Back</button></a>
        <h1>{{table_title}}</h1>

        {% if list_of_users_only == "true" %}
        <form>
            <label>View By Year Level:</label>
            <div style="width: 30%; margin-bottom: 10px;">
                <select name="year_level" class="reg_input" required id="id_year_level" onchange="this.form.submit()">
                <option selected></option>              
                <option value="Freshmen" {% if selected_year_level == 'Freshmen' %}selected{% endif %}>Freshmen</option>              
                <option value="Sophomore" {% if selected_year_level == 'Sophomore' %}selected{% endif %}>Sophomore</option>              
                <option value="Junior" {% if selected_year_level == 'Junior' %}selected{% endif %}>Junior</option>              
                <option value="Senior" {% if selected_year_level == 'Senior' %}selected{% endif %}>Senior</option>  
              </select>
            </div>
        </form>
        {% endif %}

        <form>
            <div style="width: 30%; margin-bottom: 10px;">
                <label>Search: </label>
               <input class="reg_input" name="search" type="search" placeholder="Type something..." value="{{search}}">
            </div>
        </form>

        {% if table_title == "List of all Students" and list_of_users_only == "true" %}
            <a href="/admin/bulk-delete" style="float: right;"><button>Remove All Graduates</button></a><br>
        {% endif %} 

        <table>
            <tr class="table-header">
                <td>ID</td>
                
                {% if not table_title == "List of all Administrators" %}
                <td>Student ID</td>
                {% endif %}

                <td>First Name</td>
                <td>Middle Name</td>
                <td>Last Name</td>
                <td>Address</td>
                {% if show == "With Medical Condition" %}
                <td>Medical Condition</td>
                {% endif %}
                <td>Action</td>
            </tr>
            {% for x in users %}
            <tr>
                <td>{{ x.id }}</td>

                {% if not table_title == "List of all Administrators" %}
                <td>{{ x.student_id }}</td>
                {% endif %}

                <td>{{ x.firstname }}</td>
                <td>{{ x.middlename }}</td>
                <td>{{ x.lastname }}</td>
                <td>{{ x.address }}</td>
                {% if show == "With Medical Condition" %}
                <td>{{ x.medical_condition }}</td>
                {% endif %}
                <td>
                    <a href="{% url 'check_user' x.id %}" type="submit" class="btn"><button>Show Record</button></a>
                    <a href="{% url 'delete_user' x.id %}" type="submit" class="confirmbtn"><button>Delete</button></a>
                </td>
            </tr>
            {% endfor %}
            </table>
            {% if empty_rec == "" %}
                <div style="padding:1rem; display:flex;flex-wrap:wrap;flex-direction:column;align-content:center; background-color:rgba(255, 0, 0, 0.353);">No Record Found</div>
            {% endif %}
   
{% endblock %}